### ISSUE TITLE
Relax docutils pin to allow build to support sphinx>=6 and python>=3.11

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/sphinx_rtd_theme-feedstock#28]
Hey guys, the pin on docutils in your meta file makes this package not able to support the latest sphinx and python >=3.11. See example minimal en that fails to solve:

```yaml
---
name: sphinx-py311
channels:
  - conda-forge
  - nodefaults

dependencies:
  - sphinx ==6.1.3
  - python ==3.11
  - sphinx_rtd_theme
```

This results in:
```
Could not solve for environment specs
Encountered problems while solving:
  - package sphinx-6.1.3-pyhd8ed1ab_0 requires docutils >=0.18,<0.20, but none of the providers can be installed
```

If you don't mind me, I'll try a PR freeing up the pin on docutils now :+1:
